# Build GitHub pages
name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.72.0
      
      - name: Generate gallery
        run: pixi run -e docs python docs/build_gallery.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
