# Build GitHub pages
name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.72.0
      
      - name: Generate gallery
        run: pixi run -e docs python docs/build_gallery.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
